language: node_js
node_js:
- '16.20.2'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=manning)
  - secure: enQAhPV0fd58raMjjCh7uVh45N6gD1fz6DmxhLJw/3OIyWrs/l+1M8akHb0Y93516JbVwmdwpbHt1WfilqadL4DvHF97T4KKQ8LK8CQsLj4oLzy0XobvHvo5Ru+UvGjuG9hIutlOfzTUuq4jY+3lfPIdEhpUUtLdVcrB7l2+rmGU42eSgL8KVo1mGz2mFwE11sKPzl+VEH+nIdu6DLBaspR3xK4P1oREEOYgulP8WaBA54GVUryMM8mZFc4GFSyKWm2lTtiqFG4t+I9bmYAlOzoK3AKrwur4hecGCuwWCT60WDU0pUMQ5EjgfoziaHZXJeqkA+1rHcGXLb4ktvKkyvbfQxlG4oCLmwFLSTWUejbz48TflkPuj87V1PGMwRwX9NpRYs14LHrwDEbOJ+otlecPCUMuBeb0+UqR/CPyCSbYaG7UImy8HJMGa/plcKLJ4Ydfo7jJr66ID8kX3Tl0lyyLuAf7/IXl0G1lS0bG94WPaF5WxXmjE+nLgCAQUbOctipHB/OR5pVCQ69wx+vIrpvRv7O3RMk/5BiMIjhDsb48buwGmu0muq5viOZsd7qQ/HqgtE7gUZdLA8/QtnZBcZPAlsoMftsHP3x25PTZKH2IeJRkVa+K9HTT7nGvh/9F7i/AnslVvzttS5w+RC4H2qxf2kbsQEbp/rxIsO4T6JU=
  # MATTERMOST_HOOK_URL
  - secure: GmqxnSQ4FyKYwFj+RZhUwISEBbw/2cmLuzuerOITpIjXFT3Kft4JgXqvPRpBOYmBFbVCLzE/nCkL8mQahK9NpX5BnbcYY6EpQa/LXuOOYh+DEledeRE5Z5+/bSmP9EJwwNTFp+WN2D1EaqUr3RFlPffMOJzSF8M57TjN31dn10oQRWJXobndwibOh52H4ebDsj5TBLhVsxpTnaihwA6dp3XnD1ELUx49j++9WA8vYLPfr/Fz3cYqrl1qp1a3GKhOO20U/0ZxhAbqdbKV3elmMX9J4HnlG2F+YMrQorVrY6LNr+00BERKdnxZ2dEk3TknQ/0zDtcWRKupqlsN4aVe084/FxvtaBhbNiEGRwJ9918F26hVwPG+wd++D8BoeRy+qxbO8hNFsTSD4NldY64WL316UUl+bFWdipc1zhc3Z/Qs2+948EyA8lgscplfpB8CU2ZxenVlWRAqvPntbvWDfE/RG9va9d3Z9LZFVDcKLMMc1AH4J/BBBkK/akOChdD2tXFHMHv9fLCrzIlzPy62Ngiwo2IoRTRoUFxXNyJP1p/a3EQmMCWi7nfR6yQTZYiBdNiAYBWmNoiE50BEoFW/OBP/dhwiXZbIjXN8DdagTETsNSMrY7jFNgsKMR1TNwozy2wRRzXP04lFnbDFAn2ZgHQ5EJxpmtiCbgMGKghrt6E=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
