language: node_js
node_js:
- '16.18.1'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=manning)
  - secure: enQAhPV0fd58raMjjCh7uVh45N6gD1fz6DmxhLJw/3OIyWrs/l+1M8akHb0Y93516JbVwmdwpbHt1WfilqadL4DvHF97T4KKQ8LK8CQsLj4oLzy0XobvHvo5Ru+UvGjuG9hIutlOfzTUuq4jY+3lfPIdEhpUUtLdVcrB7l2+rmGU42eSgL8KVo1mGz2mFwE11sKPzl+VEH+nIdu6DLBaspR3xK4P1oREEOYgulP8WaBA54GVUryMM8mZFc4GFSyKWm2lTtiqFG4t+I9bmYAlOzoK3AKrwur4hecGCuwWCT60WDU0pUMQ5EjgfoziaHZXJeqkA+1rHcGXLb4ktvKkyvbfQxlG4oCLmwFLSTWUejbz48TflkPuj87V1PGMwRwX9NpRYs14LHrwDEbOJ+otlecPCUMuBeb0+UqR/CPyCSbYaG7UImy8HJMGa/plcKLJ4Ydfo7jJr66ID8kX3Tl0lyyLuAf7/IXl0G1lS0bG94WPaF5WxXmjE+nLgCAQUbOctipHB/OR5pVCQ69wx+vIrpvRv7O3RMk/5BiMIjhDsb48buwGmu0muq5viOZsd7qQ/HqgtE7gUZdLA8/QtnZBcZPAlsoMftsHP3x25PTZKH2IeJRkVa+K9HTT7nGvh/9F7i/AnslVvzttS5w+RC4H2qxf2kbsQEbp/rxIsO4T6JU=
  # MATTERMOST_HOOK_URL
  - secure: sO9CSfgcCnhOtWpSw9/Pi7JZZhEyiKPYW1Scz6cx6It0wAqQ7AkD1Kd+pQEU2p+fLqaZ8PoBSMVFxPgDDD9rVMd5Hm1H17OER6xg1CgcrO4Vv6FoL4eMgGRoaLT6PkEReSp9PbAkW/8pj1F5Jto3jdSX5wXWXEgin8N86uCZSBsyNhFK++eTh3qQkBs+oenCoyYPVumGQGYRl19SgPkVDsncPR+5Q2S7EOd0vaccrSd48T11jCM9SlBuEOd8E4fE3OwIq6GEMmM7kJ9Dy/Z07g46AOGta4S2RXwzEgi3lD/g+twlxjVEmxN0tJgU3OoioDF9JjQWT5Znq5U9Zz30ZRxTuEry69kLTfBxrib9PbsSJzm1lTN1zta/S+txSYssCgptCDhY8ecyleUN16zEmcyjvvxKsnHRgmKPHBkGhw6saIT9FX8Bp13IzzNsNPxMh+6lKBlvLLqOnuWooq8f7BF0172NKKlK4tZ4SRvwqlTO3kt+ZH+cZbbPJcpVwBmlqbqtDw98hwPiID5rdvHpCmTWO4JONz5zaxHFRRcyV0XYWOcg5K9An/J/LXIDsDfwktERs6pUwYAu7fsDwuzNmojk3LPIIFNnPgg1m6PMXKJJaauccP+WuA6kzlR66+O5bkPUB2iGjmUv1cHw0k9k+7eJsY+ZekYzXB3XxwuxXKY=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
