language: node_js
node_js:
- '16.20.2'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=manning)
  - secure: qdwMMPC3z/lkBD+C64Jj/Jr/HNJ2hRFV8N7o1F9Gqj3X9vueIVApPeG1F6oyZnnOojWgq7m7mujPDpHc0UAhEl2dTUhDT8kzbetn1K7iGMU+G8063SHwhZyFuqefwB1VjOBM6FN+TdOQzl+TMvXhbS55DP+qpJwvjbETivlOz6O9wIincUg/Lu+LtkS4jWlLxkXuJsLNIOCk5wfqZ49a9RnoP/rEovixDdf78RpB255YYdxNy0dDdhMJVvBLb/1b2JjHTUdFQjIOGbkGj2Wo4pWPKwdJx5Yyh1SUdkaQ3bm+JmXq4LWIwvDi4GgdDv7uFraJpV992Vyjdn0aOtagkV/OaMKqsHFQbkPf2+ZyDms6WIlZt7hapw7G0LYKi/k0JOcxfQ8XtRase7IvQbgaYIcoXVyUgfxIxZPthJ/SKBp44qCjVTuJ40UniHe4/w1Nrn24JVKrWCB1/bV9I2uwYO3VPa+FDFa1XRzE5bIqYqpCHioIJa+buUCqGtYoEklSGH9DDAJ4jbK0rlR82gUNVTxgZ0arzN6OJeA1Nj3tB/iTOm4qtEsoSBah7JmLiNUGfeCtJDsTsnjkPfWRB+AD9spkUmHl7oBHBwEo21esQ/T/HcVXhxTKiQMrbOHYzWQTaqxgqsb1khvQSTxXE8PmMOf0iJHFZPw+ysNf3fj6HFs=
  # MATTERMOST_HOOK_URL
  - secure: t8kYqRfFLYCObjrUhx9afJtxu+w40BsmNtzD1s2B4RsjPiVbJaF+XkQCj1mfRpNVV/FwZDFK2bmlQBjxCwb+B3YlSGv2HBnjLKjoRaCw/WW+82MF04HMJ+Xt0OWbd5WjWf7K3dy25Qj2IBDWoWPmQ6zVIoMywzJW1TSF8yY7OBw/e0/75D6NyHNsr/b+Qj1LJlGWvCcDxYBV4FUNPqrFm2QdkdU0V/NpyNe71UtjCQEZMzgpfLTxk9eVwiy//ABhrFzmnVeywa9MFjm6AfLL5z9AWTSUg6gpaMe4s+2H2dwxK80H7pKul9bnSMoD3BPD1wPync2VVhHlsoIeQyI9wT7opjqfNrhkrQqImyQPNwDQUfBr6zYlPqj9Q+ZDanUBClWBzSzb75ly90+RXiFfjrf6d5VUkbcz6uIHtk80aAiksqMpkRStQ0C0iqiEevhctA8lkMSxKefbd9TJ+O8LGJq4puio0J5ICDGks1Sm90yiwXpm/VLlS/uDOT58I6Qowszj9bAFgI5IwinOIBbyq/eaplrBnOosuJlfbBWTLTNZZwPCdddWqm623tsD5cFdRr+wJFUPfAeXmKOiYFlboCuU3ODdQiTQCZUZ6WyOuBar2HYBcIpkznPMvJ64YNfs1BAOfm2edaMciPADs0wRQxov15tXcIBz6asLD5uLKvE=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
