language: node_js
node_js:
- '16.20.2'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=manning)
  - secure: y4qw0jDNHqgGjzVeVQYb+IbVSXuKliLCt4JQz0fRpQp8CX1xQqe5Q+vQDucPdhcVHlwdAtrOMQmzjby0yU+E2hlOGjz2zXSlQm0A9f19OAsGaMfEymZMkw5ByjcJncfajqmAY2vXDGw9uhKk6CkdpCzh9bdVz157kclX6M1okucqd93eQvnq5YVenEmrTBlxsDj7AgW2q8LZv5lwVHQP+14pxQaaTZmYAhYPSyHZ82CPyysSUee3j/yK6PCFX/C7fTZ96KB2WYz22GlaKuAoeIOH3e+lufmowKhyW5hGZC//VVwgQQLyGls6j5xHoZFYhsfLTKD8uOjjtgYwh3hmOtDVm2mUYINfrjgbSuM2+fy65Bpt5MiC4YtshvNNPRnoLYyzLu3OWd3ryxJDMTiZUsBP0wZP2u2FaW9fegB49m/tXvAbG1O583+5QGPNqSCl3/K84ddjkhuJ19izyjVcEoSoJjicOmqH/5FH7ekZOWUmRpn0loq7sEw9nx2T70ayboOWDXk7WlGGYa37S1BhejP8wTivNw8fFkqQq7cHUq5UdHbStg5qOpir5ll72H8EIsHQMIOXnwgNPnVLF9r97HvHUFN9GrsWpbcducll0nWWyJO3IjXkA+ynCJ2M+uBAtHGLWBGXcrvdK0WzDq+V0yyAjEtse3N4Y3r/p22ATDY=
  # MATTERMOST_HOOK_URL
  - secure: t8kYqRfFLYCObjrUhx9afJtxu+w40BsmNtzD1s2B4RsjPiVbJaF+XkQCj1mfRpNVV/FwZDFK2bmlQBjxCwb+B3YlSGv2HBnjLKjoRaCw/WW+82MF04HMJ+Xt0OWbd5WjWf7K3dy25Qj2IBDWoWPmQ6zVIoMywzJW1TSF8yY7OBw/e0/75D6NyHNsr/b+Qj1LJlGWvCcDxYBV4FUNPqrFm2QdkdU0V/NpyNe71UtjCQEZMzgpfLTxk9eVwiy//ABhrFzmnVeywa9MFjm6AfLL5z9AWTSUg6gpaMe4s+2H2dwxK80H7pKul9bnSMoD3BPD1wPync2VVhHlsoIeQyI9wT7opjqfNrhkrQqImyQPNwDQUfBr6zYlPqj9Q+ZDanUBClWBzSzb75ly90+RXiFfjrf6d5VUkbcz6uIHtk80aAiksqMpkRStQ0C0iqiEevhctA8lkMSxKefbd9TJ+O8LGJq4puio0J5ICDGks1Sm90yiwXpm/VLlS/uDOT58I6Qowszj9bAFgI5IwinOIBbyq/eaplrBnOosuJlfbBWTLTNZZwPCdddWqm623tsD5cFdRr+wJFUPfAeXmKOiYFlboCuU3ODdQiTQCZUZ6WyOuBar2HYBcIpkznPMvJ64YNfs1BAOfm2edaMciPADs0wRQxov15tXcIBz6asLD5uLKvE=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
